### ISSUE TITLE
Etcd restore script appears to fail on RKE1

### ISSUE THREAD

**Issue by nnewc** [rancherlabs/support-tools#191]
I'm trying to perform an etcd snapshot restore on a cluster that is provisioned with RKE cli and has an nginx pod deployed to represent a user workload. The restore script appears to encounter an error does not start a restored etcd container.

during restore script:
```bash
sed: unrecognized option '--name=etcd'
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...
```

after script finishes:
```bash
ubuntu@ip-10-0-0-220:~$ docker logs etcd
Error: No such container: etcd
```

RKE CLI version: 1.3.14
Kubernetes version: 1.20.15

cluster.yml:
```yaml
nodes:
    - address: X.X.X.X
      user: ubuntu
      role:
        - controlplane
        - etcd
        - worker
kubernetes_version: v1.20.15-rancher1-4
services:
  kube-api:
    secrets-encryption-config:
      enabled: true
```
I have attached full log output. Let me know if you need more info:
[etcd-restore.log](https://github.com/rancherlabs/support-tools/files/9804800/etcd-restore.log)
